version: "3.9"

services:
  client:
    build: ./client
    ports:
      - "80:80"

  books-service:
    build: ./books-service
    ports:
      - "8001:8001"

  feedback-service:
    build: ./feedback-service
    ports:
      - "8003:8003"

  notifications-service:
    build: ./notifications-service
    ports:
      - "8004:8004"

  reservations-service:
    build: ./reservations-service
    ports:
      - "8005:8005"

  stats-service:
    build: ./stats-service
    ports:
      - "8006:8006"

  users-service:
    build:
      context: ./users-service
      dockerfile: Dockerfile
    ports:
      - "8002:8002"
    environment:
      - MONGO_URI=mongodb://db:27017/library
    depends_on:
      - db

  login-service:
    build:
      context: ./login-service
      dockerfile: Dockerfile
    ports:
      - "8010:8010"
    environment:
      - MONGO_URI=mongodb://db:27017/library
      - SECRET_KEY=supersecretkey
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    depends_on:
      - db

  db:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
